apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: life-tracker-production
spec:
    replicas: 3
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    selector:
        matchLabels:
            app: frontend-deployment
    template:
        metadata:
            labels:
                app: frontend-deployment
        spec:
            automountServiceAccountToken: false
            containers:
                -   name: frontend-deployment
                    resources:
                        limits:
                            cpu: "0.5"
                            memory: "512Mi"
                        requests:
                            cpu: "0.2"
                            memory: "256Mi"
                    image: "rhaversen/life-tracker-frontend:c7c6f5d434bb21d173e73e53b2acbfa24f751fcc"
                    imagePullPolicy: Always
                    livenessProbe:
                        httpGet:
                            path: service/livez
                            port: 3000
                        periodSeconds: 10
                        initialDelaySeconds: 15
                        failureThreshold: 5
                    readinessProbe:
                        httpGet:
                            path: service/readyz
                            port: 3000
                        periodSeconds: 10
                        initialDelaySeconds: 15
                        failureThreshold: 5
                    ports:
                        -   containerPort: 5000
                    envFrom:
                        -   secretRef:
                                name: frontend-secrets
