apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: gaslight-staging
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    selector:
        matchLabels:
            app: frontend-deployment
    template:
        metadata:
            labels:
                app: frontend-deployment
        spec:
            automountServiceAccountToken: false
            containers:
                -   name: frontend-deployment
                    resources:
                        limits:
                            cpu: "400m"
                            memory: "300M"
                        requests:
                            cpu: "250m"
                            memory: "200M"
                    image: "rhaversen/gaslight-frontend:aa748b27efe866e3dd681967e86a58b3f055e5f2"
                    imagePullPolicy: Always
                    livenessProbe:
                        httpGet:
                            path: service/livez
                            port: 3000
                        periodSeconds: 10
                        initialDelaySeconds: 15
                        failureThreshold: 5
                    readinessProbe:
                        httpGet:
                            path: service/readyz
                            port: 3000
                        periodSeconds: 10
                        initialDelaySeconds: 15
                        failureThreshold: 5
                    ports:
                        -   containerPort: 5000
                    envFrom:
                        -   secretRef:
                                name: frontend-secrets
