apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deployment
    namespace: life-tracker-production
spec:
    replicas: 2
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    selector:
        matchLabels:
            app: backend-deployment
    template:
        metadata:
            labels:
                app: backend-deployment
        spec:
            automountServiceAccountToken: false
            containers:
                - name: backend-deployment
                  resources:
                      limits:
                          cpu: "400m"
                          memory: "300M"
                      requests:
                          cpu: "250m"
                          memory: "200M"
                  image: "rhaversen/life-tracker-backend:fae0fbf77f5be5a362e1a89cf9b4ed44e673fabb"
                  imagePullPolicy: Always
                  livenessProbe:
                      httpGet:
                          path: /api/service/livez
                          port: 5000
                      periodSeconds: 10
                      initialDelaySeconds: 15
                      failureThreshold: 5
                  readinessProbe:
                      httpGet:
                          path: /api/service/readyz
                          port: 5000
                      periodSeconds: 10
                      initialDelaySeconds: 15
                      failureThreshold: 5
                  ports:
                      - containerPort: 5000
                  envFrom:
                      - secretRef:
                            name: backend-secrets
