apiVersion: batch/v1
kind: CronJob
metadata:
  name: tournament-runner-production
  namespace: gaslight-staging
spec:
  schedule: "0 0 * * *"  # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: tournament-runner-production
        spec:
          restartPolicy: Never
          automountServiceAccountToken: false
          containers:
            - name: tournament-runner-production
              image: "rhaversen/gaslight-code-runner:07ae97493951a2eed5b9fb17cc592fffc1e2a324"
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "500m"
                  memory: "1024M"
                requests:
                  cpu: "250m"
                  memory: "512M"
              envFrom:
                - secretRef:
                    name: tournament-runner-secrets
